version: '3'
# ejemplo de un servicio MySQL con variables de entorno
services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
# Utilizamos archivo .env de variables de entornos
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: