version: '3.8'
services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_USER=usuario
      - WORDPRESS_DB_PASSWORD=usuario@1
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=usuario@1
      - MARIADB_DATABASE=wordpress_db
      - MARIADB_USER=usuario
      - MARIADB_PASSWORD=usuario@1
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    restart: always
volumes: 
  mariadb_data:
  wordpress_data:
